version: '3.9'

networks:
  es-network:
    driver: bridge
  kafka-network:
    driver: bridge

volumes:
  postgres_data:
  cache_data:
  elasticsearch_data:
  zoo1_data:
  zoo1_logs:
  kafka1_data:


services:
  postgresql:
    container_name: postgresql
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=woodman_local
      - POSTGRES_USER=woodman
      - POSTGRES_PASSWORD=woodman2022!
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: on-failure

  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - cache_data:/data
    restart: on-failure

  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:7.17.4
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - es-network
    environment:
      - discovery.type=single-node
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    restart: on-failure

  # kafka-network

  zoo1:
    container_name: zookeeper-1
    image: zookeeper
    networks:
      - kafka-network
    restart: always
    hostname: zoo1
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - zoo1_data:/var/lib/zookeeper/data
      - zoo1_logs:/var/lib/zookeeper/log

  kafka1:
    container_name: kafka-1
    image: ubuntu/kafka
    depends_on:
      - zoo1
    networks:
      - kafka-network
    restart: always
    hostname: kafka1
    ports:
      - '9092:9092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka1:9092,LISTENER_DOCKER_EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - kafka1_data:/var/lib/kafka/data

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    depends_on:
      - zoo1
      - kafka1
    networks:
      - kafka-network
    ports:
      - 81:8080
    environment:
      KAFKA_CLUSTERS_0_NAME: LOCAL
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka1:9092
