server:
  port: 10001

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_local
    driver-class-name: org.postgresql.Driver
    username: woodman
    password: woodman2022!
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  redis:
    host: localhost
    port: 6379
  elasticsearch:
    uris: http://localhost:9200