### register Customer
POST {{baseUrl}}/api/v1/customers
Content-Type: application/json

{
  "customerName": "jeongyong",
  "email": null,
  "password": null,
  "phoneNumber": null
}

### get customer
GET {{baseUrl}}/api/v1/customers/-1